spring:
  application:
    name: departament-service
  config:
    import: optional:configserver:http://localhost:8888/

#  datasource:
#    url: jdbc:mysql://localhost:3306/departament_db
#    username: root
#    password: 123456789
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
